---
name: historical-update
on:
  schedule:
    - cron: '10 0 * * 1'
  workflow_dispatch:

jobs:
  badge-update:
    runs-on: ubuntu-latest
    container: docker.io/golang:1.22
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.KUBEVIRT_BOT_TOKEN }}
    - name: batch update for kubevirt/kubevirt
      env:
        GITHUB_TOKEN: ${{ secrets.KUBEVIRT_BOT_TOKEN }}
        SOURCE: kubevirt/kubevirt
      run: |
        echo -n $GITHUB_TOKEN > $(pwd)/token
        export GITHUB_TOKEN_PATH=$(pwd)/token

        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode fetch \
          --target-metric retests-to-merge \
          --log-level debug
        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode plot \
          --target-metric retests-to-merge \
          --log-level debug

        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode fetch \
          --target-metric time-to-merge \
          --log-level debug
        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode plot \
          --target-metric time-to-merge \
          --log-level debug

        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode fetch \
          --target-metric merge-queue-length \
          --log-level debug
        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode plot \
          --target-metric merge-queue-length \
          --log-level debug

        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode fetch \
          --target-metric merged-prs \
          --log-level debug
        go run ./cmd/batch \
          --gh-token $(pwd)/token \
          --path $(pwd)/output \
          --mode plot \
          --target-metric merged-prs \
          --log-level debug

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: KubeVirt Bot
        author_email: kubevirtbot@redhat.com
        message: 'Historical data updated'
        add: 'output/*'
